defmodule BeaverColony.Building do
  @moduledoc """
  Where a colony builds, and when.

  Generated by `mix phx.gen.live` with the colony scope, which filters every query by
  colony. Writes also check the scope's ability, which the generator can't know about.
  """

  import Ecto.Query, warn: false
  alias BeaverColony.Repo

  alias BeaverColony.Building.Site
  alias BeaverColony.Accounts.Scope

  @doc """
  Subscribes to scoped notifications about any site changes.

  The broadcasted messages match the pattern:

    * {:created, %Site{}}
    * {:updated, %Site{}}
    * {:deleted, %Site{}}

  """
  def subscribe_sites(%Scope{} = scope) do
    key = scope.colony.id

    Phoenix.PubSub.subscribe(BeaverColony.PubSub, "colony:#{key}:sites")
  end

  defp broadcast_site(%Scope{} = scope, message) do
    key = scope.colony.id

    Phoenix.PubSub.broadcast(BeaverColony.PubSub, "colony:#{key}:sites", message)
  end

  @doc """
  Returns the list of sites.

  ## Examples

      iex> list_sites(scope)
      [%Site{}, ...]

  """
  def list_sites(%Scope{} = scope) do
    Repo.all(
      from s in Site, where: s.colony_id == ^scope.colony.id, order_by: [s.river_mile, s.name]
    )
  end

  @doc """
  Gets a single site.

  Raises `Ecto.NoResultsError` if the Site does not exist.

  ## Examples

      iex> get_site!(scope, 123)
      %Site{}

      iex> get_site!(scope, 456)
      ** (Ecto.NoResultsError)

  """
  def get_site!(%Scope{} = scope, id) do
    Repo.get_by!(Site, id: id, colony_id: scope.colony.id)
  end

  @doc """
  Creates a site.

  ## Examples

      iex> create_site(scope, %{field: value})
      {:ok, %Site{}}

      iex> create_site(scope, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_site(%Scope{} = scope, attrs) do
    with :ok <- authorize(scope, :manage_sites),
         {:ok, site = %Site{}} <-
           %Site{}
           |> Site.changeset(attrs, scope)
           |> Repo.insert() do
      broadcast_site(scope, {:created, site})
      {:ok, site}
    end
  end

  @doc """
  Updates a site.

  ## Examples

      iex> update_site(scope, site, %{field: new_value})
      {:ok, %Site{}}

      iex> update_site(scope, site, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_site(%Scope{} = scope, %Site{} = site, attrs) do
    true = site.colony_id == scope.colony.id

    with :ok <- authorize(scope, :manage_sites),
         {:ok, site = %Site{}} <-
           site
           |> Site.changeset(attrs, scope)
           |> Repo.update() do
      broadcast_site(scope, {:updated, site})
      {:ok, site}
    end
  end

  @doc """
  Deletes a site.

  ## Examples

      iex> delete_site(scope, site)
      {:ok, %Site{}}

      iex> delete_site(scope, site)
      {:error, %Ecto.Changeset{}}

  """
  def delete_site(%Scope{} = scope, %Site{} = site) do
    true = site.colony_id == scope.colony.id

    with :ok <- authorize(scope, :manage_sites),
         {:ok, site = %Site{}} <-
           Repo.delete(site) do
      broadcast_site(scope, {:deleted, site})
      {:ok, site}
    end
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking site changes.

  ## Examples

      iex> change_site(scope, site)
      %Ecto.Changeset{data: %Site{}}

  """
  def change_site(%Scope{} = scope, %Site{} = site, attrs \\ %{}) do
    true = site.colony_id == scope.colony.id

    Site.changeset(site, attrs, scope)
  end

  defp authorize(scope, ability) do
    if Scope.can?(scope, ability), do: :ok, else: {:error, :unauthorized}
  end
end
