defmodule BeaverColony.Dams do
  @moduledoc """
  A colony's dam, built one stick at a time.

  Generated by `mix phx.gen.context` with the colony scope, which gave every function
  its colony filter and scoped PubSub topic. What the generator can't know is who may
  do what, so `create_stick/2` and `delete_stick/2` check the scope's ability, as every
  write in this app does.
  """

  import Ecto.Query, warn: false
  alias BeaverColony.Repo

  alias BeaverColony.Dams.Stick
  alias BeaverColony.Accounts.Scope

  @doc """
  Subscribes to scoped notifications about any stick changes.

  The broadcasted messages match the pattern:

    * {:created, %Stick{}}
    * {:deleted, %Stick{}}

  """
  def subscribe_sticks(%Scope{} = scope) do
    key = scope.colony.id

    Phoenix.PubSub.subscribe(BeaverColony.PubSub, "colony:#{key}:sticks")
  end

  defp broadcast_stick(%Scope{} = scope, message) do
    key = scope.colony.id

    Phoenix.PubSub.broadcast(BeaverColony.PubSub, "colony:#{key}:sticks", message)
  end

  @doc """
  Returns the colony's sticks in the order they were placed, with who placed them.
  """
  def list_sticks(%Scope{} = scope) do
    Repo.all(
      from s in Stick,
        where: s.colony_id == ^scope.colony.id,
        order_by: [s.inserted_at, s.id],
        preload: :beaver
    )
  end

  @doc """
  Gets a single stick.

  Raises `Ecto.NoResultsError` if the Stick does not exist.
  """
  def get_stick!(%Scope{} = scope, id) do
    Repo.get_by!(Stick, id: id, colony_id: scope.colony.id)
  end

  @doc """
  Places a stick on the dam. Needs `:place_stick`. The stick records who placed it.
  """
  def create_stick(%Scope{} = scope, attrs) do
    with :ok <- authorize(scope, :place_stick),
         {:ok, stick = %Stick{}} <-
           %Stick{}
           |> Stick.changeset(attrs, scope)
           |> Repo.insert() do
      broadcast_stick(scope, {:created, stick})
      {:ok, stick}
    end
  end

  @doc """
  Pulls a stick out of the dam. Needs `:remove_stick`.

  Sticks aren't edited: once placed, a stick stays where it fell, and the ones above
  it rest on it.
  """
  def delete_stick(%Scope{} = scope, %Stick{} = stick) do
    true = stick.colony_id == scope.colony.id

    with :ok <- authorize(scope, :remove_stick),
         {:ok, stick = %Stick{}} <-
           Repo.delete(stick) do
      broadcast_stick(scope, {:deleted, stick})
      {:ok, stick}
    end
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking stick changes.
  """
  def change_stick(%Scope{} = scope, %Stick{} = stick, attrs \\ %{}) do
    true = stick.colony_id == scope.colony.id

    Stick.changeset(stick, attrs, scope)
  end

  @doc """
  Where each stick rests: `[{stick, row}]`, row 0 at the bottom.

  Sticks fall in the order they were placed. Each one rests on the highest earlier
  stick it overlaps, or on the riverbed if it overlaps none. Pulling a stick out lets
  the ones above it settle.
  """
  def layout(sticks) do
    sticks
    |> Enum.reduce([], fn stick, placed ->
      row =
        placed
        |> Enum.filter(fn {other, _row} -> overlaps?(stick, other) end)
        |> Enum.map(fn {_other, row} -> row + 1 end)
        |> Enum.max(fn -> 0 end)

      [{stick, row} | placed]
    end)
    |> Enum.reverse()
  end

  defp overlaps?(a, b), do: a.x < b.x + b.length and b.x < a.x + a.length

  defp authorize(scope, ability) do
    if Scope.can?(scope, ability), do: :ok, else: {:error, :unauthorized}
  end
end
